### ISSUE TITLE
Fix vext.libtorrent to work with pipenv

### ISSUE THREAD

**Issue by aresch** [spritzle/spritzle#28]
Can't run pipenv lock with vext.libtorrent installed. Without this package working we will have to resort to using --system-packages option which isn't ideal.

```
$ pipenv lock --verbose
Locking [dev-packages] dependencies…

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pipenv/resolver.py", line 85, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/pipenv/resolver.py", line 37, in main
    import pipenv.core
  File "/home/aresch/.local/share/virtualenvs/spritzle-WJROkGy7/lib/python3.6/site-packages/vext/gatekeeper/__init__.py", line 204, in load_module
    raise ImportError("No module named %s" % modulename)
ImportError: No module named pipenv
```

**Comment by gazpachoking** [comment]
This error looks a bit different than upstream, but there is a ticket about pipenv there too: stuaxo/vext#44

**Comment by stuaxo** [comment]
I can't reproduce this.  pipenv seems to work for me after installing vext.libtorrent.

**Comment by stuaxo** [comment]
BTW, spritzle looks very handy, wish I had it 3 years ago when I used bittorrent in a comercial project to download content.

**Comment by aresch** [comment]
Hmm, I'll give it another shot. Maybe something has changed since the last time I tried it.

**Comment by aresch** [comment]
It still didn't work when I tried it again, but I just decided to switch to poetry instead of pipenv and it seems work fine with it.

**Comment by stuaxo** [comment]
I think there's something in pipenv that makes it fundamentally incompatible (though I havent looked).

Vext is a hack on top of setuptools (which is a hack on top of distutils).

TBH we should burn python packaging and start again, but Pypi and pip work well enough.
